### ISSUE TITLE
attempt to call field 'register_stair_and_slab' (a nil value)

### ISSUE THREAD

**Issue by greencopper** [tenplus1/bakedclay#1]
01:19:26: ERROR[main]: ========== ERROR FROM LUA ===========
01:19:26: ERROR[main]: Failed to load and run script from 
01:19:26: ERROR[main]: /home/green/minetest/minetest-run/bin/../games/minetest_game/mods/bakedclay/init.lua:
01:19:26: ERROR[main]: ...n/bin/../games/minetest_game/mods/bakedclay/init.lua:49: attempt to call field 'register_stair_and_slab' (a nil value)
01:19:26: ERROR[main]: stack traceback:
01:19:26: ERROR[main]:  ...n/bin/../games/minetest_game/mods/bakedclay/init.lua:49: in main chunk
01:19:26: ERROR[main]: ======= END OF ERROR FROM LUA ========
01:19:26: ERROR[main]: Server: Failed to load and run /home/green/minetest/minetest-run/bin/../games/minetest_game/mods/bakedclay/init.lua
01:19:26: ERROR[main]: ERROR: An unhandled exception occurred: ModError: Failed to load and run /home/green/minetest/minetest-run/bin/../games/minetest_game/mods/bakedclay/init.lua

In thread b6c6b700:
/home/green/minetest/minetest-run/src/main.cpp:880: int main(int, char**): Assertion '0' failed.
Debug stacks:
DEBUG STACK FOR THREAD b6c6b700:
#0  int main(int, char**)
(Leftover data: #1  Dedicated server branch)
Afbrudt (SIGABRT)

This is on 0.4.11 and 0.4.12 both.

**Comment by greencopper** [comment]
SOLVED: This conflicted with the mod "morestairs". Solution: Don't run with morestairs.

**Comment by tenplus1** [comment]
I'd recommend using stairsplus: https://forum.minetest.net/viewtopic.php?id=6140
