### ISSUE TITLE
conflict moreblocks

### ISSUE THREAD

**Issue by 00c** [tenplus1/bakedclay#2]
8 slab or 8 microblocks with one dye turn into 8 full size blocks when i register it to moreblocks.
This bug exist in old version too 1 slab or micro block turns into 1 full size block.

> stairsplus:register_all("bakedclay", "white", "bakedclay:white", {
		description = "White Baked Clay",
		tiles = {"baked_clay_white.png"},
		groups = {cracky = 3, bakedclay = 1},
		default.node_sound_stone_defaults(),
	})

**Comment by tenplus1** [comment]
Sadly stairsplus within moreblocks is to blame for this problem, it registers any whole node as stairs with groups in tact, so bakedclay=1 is added to stairs making it possible to craft them as new stairs also...  This has been fixed by adding proper registration for stairsplus inside mod.

**Comment by 00c** [comment]
Thank you
